[{
  shouldDeps: [
    {
      elems: [
        'awards',
        'buy',
        'countries',
        'description',
        'director',
        'discussion',
        'duration',
        'image',
        'is-premiere',
        'is-today',
        'language',
        'list',
        'name',
        'orig-name',
        'rating',
        'schedule',
        'schedule-duration',
        'show-more',
        'subs',
        'tvpg',
        'year'
      ],
    }
  ]
}]